# Generated by Django 5.2.6 on 2025-10-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexion',
            name='port_dst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conexion',
            name='protocolo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
