# Generated by Django 5.2.6 on 2025-10-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="correo",
            field=models.EmailField(max_length=254),
        ),
    ]
