# Generated by Django 5.2.6 on 2025-10-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0002_alter_personal_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
