# Generated by Django 5.2.6 on 2025-10-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0003_personal_is_staff_personal_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
