# Generated by Django 5.2.6 on 2025-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personales', '0004_blacklistedtoken'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(fields=('usuario',), name='unique_usuario'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(fields=('correo',), name='unique_correo'),
        ),
    ]
