# Generated by Django 5.2.6 on 2025-11-13 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ataques', '0001_initial'),
        ('mitigaciones', '0002_alter_mitigacion_ejecutado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigacion',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mitigacion',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitigacion',
            name='resultado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='mitigacion',
            constraint=models.UniqueConstraint(fields=('ip',), name='unique_ip_global'),
        ),
    ]
