# Generated by Django 5.2.6 on 2025-09-20 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('ip_destino', models.CharField(blank=True, max_length=45, null=True)),
                ('puerto', models.IntegerField(blank=True, null=True)),
                ('fecha_detectado', models.DateTimeField(auto_now_add=True)),
                ('conteo_conexiones', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('ip_src', models.CharField(max_length=45)),
                ('ip_dst', models.CharField(max_length=45)),
                ('port_dst', models.IntegerField()),
                ('etiqueta', models.CharField(max_length=50)),
                ('confianza', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero', models.DecimalField(decimal_places=0, max_digits=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_mitigacion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('ataque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigaciones', to='app.ataque')),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.personal')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='app.rol'),
        ),
    ]
